### ISSUE TITLE
GithubRelease failed: POST https://api.github.com/repos/.../releases: 401 Bad credentials []

### ISSUE THREAD

**Issue by schollz** [goreleaser/releaser#38]
How do you let releaser use the Github credentials?

**Comment by jspc** [comment]
There's an env var `GITHUB_TOKEN` which I'll make sure is better documented.

Perhaps a branch to default to the creds is appropriate too.

**Comment by schollz** [comment]
Thanks, [found the Github docs](https://help.github.com/articles/creating-an-access-token-for-command-line-use/).

**Comment by jspc** [comment]
> default to the creds

Sorry, I just realised that's a nonsense statement, I'm working on aws creds elsewhere and completely mucked that up. I was thinking github had some default creds location.

That being said; perhaps some global config for types, keys is sensible

**Comment by jspc** [comment]
@schollz- I'll make sure that's there too
