### ISSUE TITLE
Am I doing this wrong?

### ISSUE THREAD

**Issue by zet4** [goreleaser/releaser#40]
So I decided to free up some time and built a small experiment repo where I tried to build a minimal docker image with travis but now I also wanted to add a release for tags, problem is it just won't build, I used the snippet provided in readme, here's a link to travis [build log](https://travis-ci.org/zet4/go-travis-docker-test/builds/188629592).

**Comment by jspc** [comment]
@zet4 - thats interesting, I get the same thing locally:

```bash
$ curl -s -L -o /tmp/release.tar.gz https://github.com/goreleaser/releaser/releases/download/v0.2.4/release_Darwin_x86_64.tar.gz
$ tar -xf /tmp/release.tar.gz -C /var/folders/zg/b74twzq53s16tnz_sd68v_sh0000gn/T/
$ /tmp/release.tar.gz: gzip compressed data
$ gunzip /tmp/release.tar.gz
gunzip: /tmp/release.tar.gz: unexpected end of file
gunzip: /tmp/release.tar.gz: uncompress failed
```

I suspect the pushed version isn't quite right. I've restarted the release build. Give it a go in a couple of minutes and report back.

**Comment by jspc** [comment]
@zet4, @caarlos0 found the issue: https://github.com/goreleaser/releaser/commit/40de5c5c644d69c3d33a6d0cf16e539a0f40423b#commitcomment-20351067

Give me five minutes to sort it out.

**Comment by caarlos0** [comment]
Just pushed tag v0.2.5, this should fix the issue...
