### ISSUE TITLE
Consider using zip for windows builds

### ISSUE THREAD

**Issue by zet4** [goreleaser/releaser#45]
Currently releaser builds archives for all 3 destinations as tar.gz, windows doesn't support opening these archives out-of-the-box and requires 7-zip to be installed, which to normal users might be troublesome, consider adding option to archive files for windows as zip.

**Comment by caarlos0** [comment]
makes sense. Thanks!

**Comment by caarlos0** [comment]
@zet4 check #52

**Comment by zet4** [comment]
Sure that sounds good 👍
