### ISSUE TITLE
`releaser --init`

### ISSUE THREAD

**Issue by jspc** [goreleaser/releaser#47]
Generate a skeleton `releaser.yml` file based on the `origin` remote of the repo.

This wont be a perfect tool; `origin` almost certainly wont point to the correct place when forking and working within `GOROOT`, but it ought to work well enough for new projects and to provide sensible values for CIs

**Comment by caarlos0** [comment]
Seems like a good feature to have.

**Comment by caarlos0** [comment]
Since #74 I guess this is not needed anymore.
