### ISSUE TITLE
allow ldflags customization?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/releaser#5]

**Comment by caarlos0** [comment]
`-X main.version=tagname` ldflag document in 87c5d8651bf6a981ef6b86af5a918f2dfad04a87.

**Comment by caarlos0** [comment]
@JoshuaKolden, @schollz and @jorinvo, can you check if #60 works well enough for your use cases?

**Comment by schollz** [comment]
Thanks, it looks great

**Comment by caarlos0** [comment]
@schollz thanks!

released in v0.3.2
