### ISSUE TITLE
Homebrew formulae improvements

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/releaser#50]
The homebrew tap is a little hacky to support linuxbrew (getting os from uname).

I was thinking:

- is linuxbrew support really required?
- is anyone still using i386 macs?

Maybe we could simplify it by just using the `Darwin_x86_64` build directly.

**Comment by caarlos0** [comment]
also check https://github.com/Linuxbrew/brew/issues/220

**Comment by jorinvo** [comment]
Also would be nice to add the `sha` value to the formula.
Right now I get a warning when installing:
```
Warning: Cannot verify integrity of name.tar.gz
A checksum was not provided for this resource
For your reference the SHA256 is: ...
```
