### ISSUE TITLE
Create initial release?

### ISSUE THREAD

**Issue by embano1** [goreleaser/releaser#54]
Hi,

not sure if I got this wrong, but the first "curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash" only works for me when there´s already two tags with at least one commit diff present. The error is "exit status 128: fatal: Not a valid object name v1^" when there´s only one tag present.

What I want to achieve is

1) create new repo
2) create first release (e.g. only 1 commit, 1 tag)
3) call goreleaser

Is this by design, am I doing something wrong or is this a bug?

Thx for your efforts. I like the tool.

**Comment by caarlos0** [comment]
@embano1 this is probably a bug, let me check

**Comment by caarlos0** [comment]
This indeed happens if you have only one commit and one tag.

I don't yet know how to solve this in a good way...

### how to reproduce

```console
mkdir newrepo
cd $_
git init
touch file
git add -A
git commit -m 'first'
git tag v0.0.1
git describe --tags --abbrev=0 --always
git describe --tags --abbrev=0 --always v0.0.1^ # fatal: Not a valid object name v0.0.1^
```

**Comment by embano1** [comment]
thank you for the quick feedback.
well, any idea how would i work around this issue then? not sure if it was also not working when there were two commits and just one tag, e.g. several commits going in the same (tag) v0.1 release.

**Comment by caarlos0** [comment]
@embano1 Yes, two commits work:

```console
mkdir newrepo
cd $_
git init
touch file
git add -A
git commit -m 'first'
touch file2
git add -A
git commit -m 'second'
git tag v0.0.1
git describe --tags --abbrev=0 --always
git describe --tags --abbrev=0 --always v0.0.1^ # first commit SHA
```

**Comment by embano1** [comment]
Ok, I can live with that as a workaround :)

**Comment by caarlos0** [comment]
Ok then. I'll leave it as-is.

thanks for the report anyway =)
