### ISSUE TITLE
Brew releasing requires formula file to exist

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/releaser#66]
Brew releasing only works when the formula file already exist in the specified Git repository.
I added an empty file to make it work.
I think the problem is the use of `UpdateFile` here: https://github.com/goreleaser/releaser/blob/master/pipeline/brew/brew.go#L74
Maybe we can consider using `CreateFile` when the updating fails?

**Comment by caarlos0** [comment]
This was fixed on https://github.com/goreleaser/releaser/commit/2aec3dff4201980c1412643e8ce037b85aff9049, but I think the code can be improved, I'll work on it.

**Comment by jorinvo** [comment]
Thank you! I discovered this before this version. 
Can I close this issue then?

**Comment by caarlos0** [comment]
I just opened a PR improving the code, so it should be more robust now.

When I merge it this issue will close :)

You can take a look if you want: #70
