### ISSUE TITLE
Support for Homebrew formula in subdirectories

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/releaser#67]
As mentioned [here](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#creating-a-tap) it's possible (and suggested) to keep formulas of a tap in a subdirectory. 
Either there could be a new option to specify the `dir` to write to, or even simpler would be to add it to the current `repo` option:

To save it on the top level (as currently supported) nothing would change:

```yml
brew:
  repo: user/homebrew-tap
```

To use the `Formula` subdirectory instead you would do:

```yaml
brew:
  repo: user/homebrew-tap/Formula
```

Am I missing any cases where this might conflict?

**Comment by caarlos0** [comment]
Good idea, but I think its better declare it as:

```yml
brew:
  repo: user/homebrew-tap
  folder: Formula
```

Since `repo` is just the repository, not the path...

**Comment by jorinvo** [comment]
@caarlos0 yes, you are right. Better to be explizit.

**Comment by caarlos0** [comment]
Nice, will work on it right now!

**Comment by caarlos0** [comment]
@jorinvo #71 🍺

**Comment by jorinvo** [comment]
@caarlos0 thank you for the fast solution. It's simple and straight forward to use!
