### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/releaser#7]

**Comment by parnmatt** [comment]
The author can correct me if im wrong, but Windows should just work.

Looking at the code it uses **`GOOS`** AND **`GOARCH`** internally.

By default it will only use `darwin` and `linux`, but you can use any **`GOOS`**, like `windows`.

Just specify the os in the build list of the yaml configuration file. 

[See here for all valid inputs](https://golang.org/doc/install/source#environment)

**Comment by caarlos0** [comment]
Yep, but I'm not adding the binary with the `.exe` suffix... that's the only thing missing I believe...

Besides that, yeah, `GOOS=windows` should just work indeed =)
