### ISSUE TITLE
Make more configuration optional

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/releaser#74]
I also like the idea of a quick way to create a default config file (https://github.com/goreleaser/releaser/issues/47), but many projects probably have the same configuration and wouldn't even need any configuration file if the defaults are set right.

- I think in most cases the `repo` option could be parse from the `git remote`. 

- Also, many Go binaries follow the convention of naming the binary like the directory containing the `main.go` file. This could be used as `binary_name`.

Would it be useful to make those two settings optional?

**Comment by caarlos0** [comment]
This is done in #61, I guess it is easy enough to just use that code...

It would probably work... do you want to try to do it?

**Comment by jorinvo** [comment]
@caarlos0 sure!

**Comment by caarlos0** [comment]
@jorinvo I guess that if we make this two args optional, the `--init` would be kind of useless..

IMO you can [fetch that PR](https://help.github.com/articles/checking-out-pull-requests-locally/), remove the init command, add the other parts and open another PR 👍

**Comment by jorinvo** [comment]
Sounds good! I'll have a look later :)
