### ISSUE TITLE
Add lowercase versions to default files 

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/releaser#77]
https://github.com/goreleaser/releaser/blob/master/config/config.go#L14

I know it's more common to have *readme* and *license* files with uppercase, but there are also projects out there using the lowercase versions.
I guess adding them wouldn't be a big deal and might come in handy for a few people.
What do you think @caarlos0?

**Comment by caarlos0** [comment]
I think it's valid!

Check #76 , I already improved it a little. Will do it there too...

**Comment by jorinvo** [comment]
Thanks!
